basePath: /
definitions:
  Enum.RoleEnum:
    enum:
    - TUTOR
    - MANAGER
    - DOCTOR
    - SECRETARY
    - ADMIN
    type: string
    x-enum-varnames:
    - Tutor
    - Manager
    - Doctor
    - Secretary
    - Admin
  Request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  Request.RegisterRequest:
    properties:
      birthDate:
        type: string
      document:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - birthDate
    - document
    - email
    - name
    - password
    type: object
  Response.ClinicalInfo:
    properties:
      expired:
        example: false
        type: boolean
      expiresIn:
        example: "2025-04-08T21:45:00Z"
        type: string
      name:
        example: John Doe's Clinical Company'
        type: string
    type: object
  Response.ErrorResponse:
    properties:
      error:
        example: Usuário ou Senha inválidos
        type: string
    type: object
  Response.LoginResponse:
    properties:
      clinical:
        $ref: '#/definitions/Response.ClinicalInfo'
      token:
        example: firebase-token
        type: string
      user:
        $ref: '#/definitions/Response.UserInfo'
    type: object
  Response.UserInfo:
    properties:
      email:
        example: johndoe@example.com
        type: string
      name:
        example: John Doe
        type: string
      role:
        allOf:
        - $ref: '#/definitions/Enum.RoleEnum'
        example: TUTOR
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gerenciamento de clínica veterinária
  title: Vet API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Autentica o usuário e retorna tokens de acesso
      parameters:
      - description: Credenciais
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/Request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/Response.ErrorResponse'
      summary: Login com email e senha
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados do novo usuário
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/Request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Response.LoginResponse'
        "400":
          description: Requisição inválida
          schema:
            $ref: '#/definitions/Response.ErrorResponse'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/Response.ErrorResponse'
      summary: Registra um novo usuário
      tags:
      - Auth
swagger: "2.0"
