basePath: /
definitions:
  Request.UpdateSensorRequest:
    properties:
      sensor:
        type: string
      value:
        type: integer
    required:
    - sensor
    - value
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gerenciamento de clínica veterinária
  title: Vet API
  version: "1.0"
paths:
  /api/v1/sesor/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados do sensor
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/Request.UpdateSensorRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            type: boolean
        "500":
          description: Internal Server Error
          schema:
            type: boolean
      security:
      - BearerAuth: []
      summary: Atualiza um sensor
      tags:
      - Sensor
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
