name: Build-Push-PRD
'on':
  push:
    branches:
      - master
jobs:
  build-prd:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout-Repository
        uses: actions/checkout@v4

      - name: Setup-Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true
      - run: go version

      - name: Install-Golang-Dependencies
        run: go mod download

      - name: Build-Golang-App
        run: GOOS=linux go build -o build/main -v

      - name: Display-Build-Golang-App
        run: ls -R build/

      - name: Run-Unit-Test-Golang-App
        run: go test

      - name: Publish
        uses: appleboy/scp-action@master
        with:
          host: '${{ secrets.VM_HOST }}'
          username: '${{ secrets.VM_USERNAME }}'
          key: '${{ secrets.VM_SSH_KEY }}'
          port: 22
          password: '${{ secrets.PASSWORD }}'
          source: build/
          target: /home/ubuntu/weed-master

      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.VM_HOST }}'
          username: '${{ secrets.VM_USERNAME }}'
          key: '${{ secrets.VM_SSH_KEY }}'
          password: '${{ secrets.PASSWORD }}'
          port: 22
          script: |
            cd /home/ubuntu/weed-master
            ls -l
            sudo systemctl stop weedm
            sudo systemctl start weedm
            sudo systemctl status weedm
